services:
    tft_dps:
        build:
            context: .
            target: tft_dps
        ports:
            - "4725:4723"
        command: "python main.py"
    web:
        build:
            args:
                - VITE_API_URL=https://tftdpsapi.velchees.dev
            context: .
            target: web
        ports:
            - "5175:3000"
        environment:
            - VITE_API_URL=https://tftdpsapi.velchees.dev
        command: "node build"
