export const API_URL = 'http://localhost:4723'

export const DEFAULT_SEARCH_CONTEXT = () => ({
    minStars: 1,
    maxStars: 3,
    units: new Set([
        // 'Characters/TFT15_Aatrox',
        // 'Characters/TFT15_Ahri',
        // 'Characters/TFT15_Akali',
        // 'Characters/TFT15_Ashe',
        // 'Characters/TFT15_Braum',
        // 'Characters/TFT15_Caitlyn',
        // 'Characters/TFT15_Darius',
        // 'Characters/TFT15_Ezreal',
        // 'Characters/TFT15_Garen',
        // 'Characters/TFT15_Gwen',
        // 'Characters/TFT15_Janna',
        // 'Characters/TFT15_JarvanIV',
        // 'Characters/TFT15_Jayce',
        // 'Characters/TFT15_Jhin',
        // 'Characters/TFT15_Jinx',
        // 'Characters/TFT15_KSante',
        // 'Characters/TFT15_KaiSa',
        // 'Characters/TFT15_Kalista',
        // 'Characters/TFT15_Katarina',
        // 'Characters/TFT15_Kayle',
        // 'Characters/TFT15_Kennen',
        // 'Characters/TFT15_Kobuko',
        // 'Characters/TFT15_LeeSin',
        // 'Characters/TFT15_Leona',
        // 'Characters/TFT15_Lulu',
        // 'Characters/TFT15_Lux',
        // 'Characters/TFT15_Malphite',
        // 'Characters/TFT15_Malzahar',
        // 'Characters/TFT15_Naafiri',
        // 'Characters/TFT15_Poppy',
        // 'Characters/TFT15_Rakan',
        // 'Characters/TFT15_Rell',
        // 'Characters/TFT15_Ryze',
        // 'Characters/TFT15_Samira',
        // 'Characters/TFT15_Seraphine',
        // 'Characters/TFT15_Sett',
        // 'Characters/TFT15_Swain',
        // 'Characters/TFT15_Syndra',
        // 'Characters/TFT15_Udyr',
        // 'Characters/TFT15_Varus',
        // 'Characters/TFT15_Viego',
        // 'Characters/TFT15_Xayah',
        // 'Characters/TFT15_XinZhao',
        // 'Characters/TFT15_Yasuo',
        // 'Characters/TFT15_Yone',
        // 'Characters/TFT15_Yuumi',
        // 'Characters/TFT15_Zac',
        // 'Characters/TFT15_Ziggs',
        // 'Characters/TFT15_Volibear',
        // 'Characters/TFT15_Senna',
        // 'Characters/TFT15_Lucian',
        // 'Characters/TFT15_Gangplank',
        // 'Characters/TFT15_DrMundo',
        // 'Characters/TFT15_Gnar',
        // 'Characters/TFT15_Karma',
        // 'Characters/TFT15_Vi',
        // 'Characters/TFT15_Sivir',
        // 'Characters/TFT15_TwistedFate',
        // 'Characters/TFT15_Shen',
        // 'Characters/TFT15_Zyra',
        // 'Characters/TFT15_Neeko',
    ]),
    items: new Set([]),
    traits: {
        bronze: true,
        silver: true,
        gold: true,
        prismatic: false,
    },
})
